version: "3.4"

services:
  FlightsAPI:
    image: dammdeol/FlightsAPI
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000